# Makefile.in generated by automake 1.7.9 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# ------------------------------------------------------------------------
# HSENCFS (High Security EnCrypting File System)
# Fuse based encrypted file system.
# It will encrypt data on write, decrypt data on read.
#

srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/hsencfs
pkglibdir = $(libdir)/hsencfs
pkgincludedir = $(includedir)/hsencfs
top_builddir = .

am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
ACLOCAL = ${SHELL} /home/peterglen/src/hsenc/hsenc/missing --run aclocal-1.7
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/peterglen/src/hsenc/hsenc/missing --run tar
AUTOCONF = ${SHELL} /home/peterglen/src/hsenc/hsenc/missing --run autoconf
AUTOHEADER = ${SHELL} /home/peterglen/src/hsenc/hsenc/missing --run autoheader
AUTOMAKE = ${SHELL} /home/peterglen/src/hsenc/hsenc/missing --run automake-1.7
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = 
CPP = gcc -E
CPPFLAGS =   -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS =   
LIBOBJS = 
LIBS = -lulockmgr -lfuse 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/peterglen/src/hsenc/hsenc/missing --run makeinfo
OBJEXT = o
PACKAGE = hsencfs
PACKAGE_BUGREPORT = bugs@nohost.none
PACKAGE_NAME = hsencfs
PACKAGE_STRING = hsencfs 1.17
PACKAGE_TARNAME = hsencfs
PACKAGE_URL = 
PACKAGE_VERSION = 1.17
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.17
ac_ct_CC = gcc
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
bindir = ${exec_prefix}/bin
build_alias = 
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = /home/peterglen/src/hsenc/hsenc/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 

SUBDIRS = bluepoint tools docs

PAN_SERV = GNOME_HSENCApplet.server
BONOBO_DIR = /usr/lib/bonobo/servers

# Docs for distribution
dist_doc_DATA = PASSES FUSEOPTS QUICKSTART SECURITY PASSHINTS DISCLAIMER\
        hsencfs.spec hsencfs.init compall.sh hard-remove.sh \
            $(PAN_SERV).in lazy.sh compall.sh


# Scripts for askpass and tray
dist_bin_SCRIPTS = \
        hsaskpass.py                \
        hstray.py


# Auxiliaries

# Fake it into the distribution
# use: ls *.py *.sh *.server SUMFILE sha*
EXTRA_DIST = hsencrw.c hsencop.c hsicon.png hsicon.svg hspadlock.png hspadlock.svg screenshot.png study \
        checksum.sh                 \
        enctest.sh                  \
        gensum.sh                   \
        GNOME_HSENCApplet.server.in \
        lazy.sh                     \
        pack.sh                     \
        sha1.sum                    \
        sha1.sum.old                \
        SUMFILE


bin_PROGRAMS = hsencfs hsaskpass

# The main program
hsencfsdir = .
hsencfs_CFLAGS = -D_FILE_OFFSET_BITS=64 -O2 -I$(srcdir)/bluepoint \
            -lfuse -lulockmgr

hsencfs_SOURCES = hsencfs.c hsutils.c hspass.c hsutils.h
hsencfs_LDADD = bluepoint/bluepoint2.o

# Password helper
hsaskpass_CFLAGS = -D_FILE_OFFSET_BITS=64 -O2 -I$(srcdir)/bluepoint
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = hsencfs$(EXEEXT) hsaskpass$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

hsaskpass_SOURCES = hsaskpass.c
hsaskpass_OBJECTS = hsaskpass-hsaskpass.$(OBJEXT)
hsaskpass_LDADD = $(LDADD)
hsaskpass_DEPENDENCIES =
hsaskpass_LDFLAGS =
am_hsencfs_OBJECTS = hsencfs-hsencfs.$(OBJEXT) hsencfs-hsutils.$(OBJEXT) \
	hsencfs-hspass.$(OBJEXT)
hsencfs_OBJECTS = $(am_hsencfs_OBJECTS)
hsencfs_DEPENDENCIES = bluepoint/bluepoint2.o
hsencfs_LDFLAGS =
SCRIPTS = $(dist_bin_SCRIPTS)


DEFAULT_INCLUDES =  -I. -I$(srcdir) -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
DEP_FILES = ./$(DEPDIR)/hsaskpass-hsaskpass.Po \
	./$(DEPDIR)/hsencfs-hsencfs.Po \
	./$(DEPDIR)/hsencfs-hspass.Po \
	./$(DEPDIR)/hsencfs-hsutils.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = hsaskpass.c $(hsencfs_SOURCES)
DATA = $(dist_doc_DATA)


RECURSIVE_TARGETS = info-recursive dvi-recursive pdf-recursive \
	ps-recursive install-info-recursive uninstall-info-recursive \
	all-recursive install-data-recursive install-exec-recursive \
	installdirs-recursive install-recursive uninstall-recursive \
	check-recursive installcheck-recursive
DIST_COMMON = README $(dist_bin_SCRIPTS) $(dist_doc_DATA) \
	$(srcdir)/Makefile.in $(srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL Makefile.am NEWS TODO aclocal.m4 compile \
	config.h.in configure configure.ac depcomp install-sh missing \
	mkinstalldirs
DIST_SUBDIRS = $(SUBDIRS)
SOURCES = hsaskpass.c $(hsencfs_SOURCES)

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .o .obj

am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)

$(top_builddir)/config.status: $(srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck
$(srcdir)/configure:  $(srcdir)/configure.ac $(ACLOCAL_M4) $(CONFIGURE_DEPENDENCIES)
	cd $(srcdir) && $(AUTOCONF)

$(ACLOCAL_M4):  configure.ac 
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h

$(srcdir)/config.h.in:  $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOHEADER)
	touch $(srcdir)/config.h.in

distclean-hdr:
	-rm -f config.h stamp-h1
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
hsaskpass$(EXEEXT): $(hsaskpass_OBJECTS) $(hsaskpass_DEPENDENCIES) 
	@rm -f hsaskpass$(EXEEXT)
	$(LINK) $(hsaskpass_LDFLAGS) $(hsaskpass_OBJECTS) $(hsaskpass_LDADD) $(LIBS)
hsencfs$(EXEEXT): $(hsencfs_OBJECTS) $(hsencfs_DEPENDENCIES) 
	@rm -f hsencfs$(EXEEXT)
	$(LINK) $(hsencfs_LDFLAGS) $(hsencfs_OBJECTS) $(hsencfs_LDADD) $(LIBS)
dist_binSCRIPT_INSTALL = $(INSTALL_SCRIPT)
install-dist_binSCRIPTS: $(dist_bin_SCRIPTS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(dist_bin_SCRIPTS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f $$d$$p; then \
	    f=`echo "$$p" | sed 's|^.*/||;$(transform)'`; \
	    echo " $(dist_binSCRIPT_INSTALL) $$d$$p $(DESTDIR)$(bindir)/$$f"; \
	    $(dist_binSCRIPT_INSTALL) $$d$$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-dist_binSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_bin_SCRIPTS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's|^.*/||;$(transform)'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/hsaskpass-hsaskpass.Po
include ./$(DEPDIR)/hsencfs-hsencfs.Po
include ./$(DEPDIR)/hsencfs-hspass.Po
include ./$(DEPDIR)/hsencfs-hsutils.Po

.c.o:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `test -f '$<' || echo '$(srcdir)/'`$<

.c.obj:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `if test -f '$<'; then $(CYGPATH_W) '$<'; else $(CYGPATH_W) '$(srcdir)/$<'; fi`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `if test -f '$<'; then $(CYGPATH_W) '$<'; else $(CYGPATH_W) '$(srcdir)/$<'; fi`

hsaskpass-hsaskpass.o: hsaskpass.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsaskpass_CFLAGS) $(CFLAGS) -MT hsaskpass-hsaskpass.o -MD -MP -MF "$(DEPDIR)/hsaskpass-hsaskpass.Tpo" \
	  -c -o hsaskpass-hsaskpass.o `test -f 'hsaskpass.c' || echo '$(srcdir)/'`hsaskpass.c; \
	then mv -f "$(DEPDIR)/hsaskpass-hsaskpass.Tpo" "$(DEPDIR)/hsaskpass-hsaskpass.Po"; \
	else rm -f "$(DEPDIR)/hsaskpass-hsaskpass.Tpo"; exit 1; \
	fi
#	source='hsaskpass.c' object='hsaskpass-hsaskpass.o' libtool=no \
#	depfile='$(DEPDIR)/hsaskpass-hsaskpass.Po' tmpdepfile='$(DEPDIR)/hsaskpass-hsaskpass.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsaskpass_CFLAGS) $(CFLAGS) -c -o hsaskpass-hsaskpass.o `test -f 'hsaskpass.c' || echo '$(srcdir)/'`hsaskpass.c

hsaskpass-hsaskpass.obj: hsaskpass.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsaskpass_CFLAGS) $(CFLAGS) -MT hsaskpass-hsaskpass.obj -MD -MP -MF "$(DEPDIR)/hsaskpass-hsaskpass.Tpo" \
	  -c -o hsaskpass-hsaskpass.obj `if test -f 'hsaskpass.c'; then $(CYGPATH_W) 'hsaskpass.c'; else $(CYGPATH_W) '$(srcdir)/hsaskpass.c'; fi`; \
	then mv -f "$(DEPDIR)/hsaskpass-hsaskpass.Tpo" "$(DEPDIR)/hsaskpass-hsaskpass.Po"; \
	else rm -f "$(DEPDIR)/hsaskpass-hsaskpass.Tpo"; exit 1; \
	fi
#	source='hsaskpass.c' object='hsaskpass-hsaskpass.obj' libtool=no \
#	depfile='$(DEPDIR)/hsaskpass-hsaskpass.Po' tmpdepfile='$(DEPDIR)/hsaskpass-hsaskpass.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsaskpass_CFLAGS) $(CFLAGS) -c -o hsaskpass-hsaskpass.obj `if test -f 'hsaskpass.c'; then $(CYGPATH_W) 'hsaskpass.c'; else $(CYGPATH_W) '$(srcdir)/hsaskpass.c'; fi`

hsencfs-hsencfs.o: hsencfs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -MT hsencfs-hsencfs.o -MD -MP -MF "$(DEPDIR)/hsencfs-hsencfs.Tpo" \
	  -c -o hsencfs-hsencfs.o `test -f 'hsencfs.c' || echo '$(srcdir)/'`hsencfs.c; \
	then mv -f "$(DEPDIR)/hsencfs-hsencfs.Tpo" "$(DEPDIR)/hsencfs-hsencfs.Po"; \
	else rm -f "$(DEPDIR)/hsencfs-hsencfs.Tpo"; exit 1; \
	fi
#	source='hsencfs.c' object='hsencfs-hsencfs.o' libtool=no \
#	depfile='$(DEPDIR)/hsencfs-hsencfs.Po' tmpdepfile='$(DEPDIR)/hsencfs-hsencfs.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -c -o hsencfs-hsencfs.o `test -f 'hsencfs.c' || echo '$(srcdir)/'`hsencfs.c

hsencfs-hsencfs.obj: hsencfs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -MT hsencfs-hsencfs.obj -MD -MP -MF "$(DEPDIR)/hsencfs-hsencfs.Tpo" \
	  -c -o hsencfs-hsencfs.obj `if test -f 'hsencfs.c'; then $(CYGPATH_W) 'hsencfs.c'; else $(CYGPATH_W) '$(srcdir)/hsencfs.c'; fi`; \
	then mv -f "$(DEPDIR)/hsencfs-hsencfs.Tpo" "$(DEPDIR)/hsencfs-hsencfs.Po"; \
	else rm -f "$(DEPDIR)/hsencfs-hsencfs.Tpo"; exit 1; \
	fi
#	source='hsencfs.c' object='hsencfs-hsencfs.obj' libtool=no \
#	depfile='$(DEPDIR)/hsencfs-hsencfs.Po' tmpdepfile='$(DEPDIR)/hsencfs-hsencfs.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -c -o hsencfs-hsencfs.obj `if test -f 'hsencfs.c'; then $(CYGPATH_W) 'hsencfs.c'; else $(CYGPATH_W) '$(srcdir)/hsencfs.c'; fi`

hsencfs-hsutils.o: hsutils.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -MT hsencfs-hsutils.o -MD -MP -MF "$(DEPDIR)/hsencfs-hsutils.Tpo" \
	  -c -o hsencfs-hsutils.o `test -f 'hsutils.c' || echo '$(srcdir)/'`hsutils.c; \
	then mv -f "$(DEPDIR)/hsencfs-hsutils.Tpo" "$(DEPDIR)/hsencfs-hsutils.Po"; \
	else rm -f "$(DEPDIR)/hsencfs-hsutils.Tpo"; exit 1; \
	fi
#	source='hsutils.c' object='hsencfs-hsutils.o' libtool=no \
#	depfile='$(DEPDIR)/hsencfs-hsutils.Po' tmpdepfile='$(DEPDIR)/hsencfs-hsutils.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -c -o hsencfs-hsutils.o `test -f 'hsutils.c' || echo '$(srcdir)/'`hsutils.c

hsencfs-hsutils.obj: hsutils.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -MT hsencfs-hsutils.obj -MD -MP -MF "$(DEPDIR)/hsencfs-hsutils.Tpo" \
	  -c -o hsencfs-hsutils.obj `if test -f 'hsutils.c'; then $(CYGPATH_W) 'hsutils.c'; else $(CYGPATH_W) '$(srcdir)/hsutils.c'; fi`; \
	then mv -f "$(DEPDIR)/hsencfs-hsutils.Tpo" "$(DEPDIR)/hsencfs-hsutils.Po"; \
	else rm -f "$(DEPDIR)/hsencfs-hsutils.Tpo"; exit 1; \
	fi
#	source='hsutils.c' object='hsencfs-hsutils.obj' libtool=no \
#	depfile='$(DEPDIR)/hsencfs-hsutils.Po' tmpdepfile='$(DEPDIR)/hsencfs-hsutils.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -c -o hsencfs-hsutils.obj `if test -f 'hsutils.c'; then $(CYGPATH_W) 'hsutils.c'; else $(CYGPATH_W) '$(srcdir)/hsutils.c'; fi`

hsencfs-hspass.o: hspass.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -MT hsencfs-hspass.o -MD -MP -MF "$(DEPDIR)/hsencfs-hspass.Tpo" \
	  -c -o hsencfs-hspass.o `test -f 'hspass.c' || echo '$(srcdir)/'`hspass.c; \
	then mv -f "$(DEPDIR)/hsencfs-hspass.Tpo" "$(DEPDIR)/hsencfs-hspass.Po"; \
	else rm -f "$(DEPDIR)/hsencfs-hspass.Tpo"; exit 1; \
	fi
#	source='hspass.c' object='hsencfs-hspass.o' libtool=no \
#	depfile='$(DEPDIR)/hsencfs-hspass.Po' tmpdepfile='$(DEPDIR)/hsencfs-hspass.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -c -o hsencfs-hspass.o `test -f 'hspass.c' || echo '$(srcdir)/'`hspass.c

hsencfs-hspass.obj: hspass.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -MT hsencfs-hspass.obj -MD -MP -MF "$(DEPDIR)/hsencfs-hspass.Tpo" \
	  -c -o hsencfs-hspass.obj `if test -f 'hspass.c'; then $(CYGPATH_W) 'hspass.c'; else $(CYGPATH_W) '$(srcdir)/hspass.c'; fi`; \
	then mv -f "$(DEPDIR)/hsencfs-hspass.Tpo" "$(DEPDIR)/hsencfs-hspass.Po"; \
	else rm -f "$(DEPDIR)/hsencfs-hspass.Tpo"; exit 1; \
	fi
#	source='hspass.c' object='hsencfs-hspass.obj' libtool=no \
#	depfile='$(DEPDIR)/hsencfs-hspass.Po' tmpdepfile='$(DEPDIR)/hsencfs-hspass.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(hsencfs_CFLAGS) $(CFLAGS) -c -o hsencfs-hspass.obj `if test -f 'hspass.c'; then $(CYGPATH_W) 'hspass.c'; else $(CYGPATH_W) '$(srcdir)/hspass.c'; fi`
uninstall-info-am:
dist_docDATA_INSTALL = $(INSTALL_DATA)
install-dist_docDATA: $(dist_doc_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(docdir)
	@list='$(dist_doc_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(dist_docDATA_INSTALL) $$d$$p $(DESTDIR)$(docdir)/$$f"; \
	  $(dist_docDATA_INSTALL) $$d$$p $(DESTDIR)$(docdir)/$$f; \
	done

uninstall-dist_docDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_doc_DATA)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(docdir)/$$f"; \
	  rm -f $(DESTDIR)$(docdir)/$$f; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ETAGS = etags
ETAGSFLAGS =

CTAGS = ctags
CTAGSFLAGS =

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if (etags --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	else \
	  include_option=--include; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -f $$subdir/TAGS && \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$tags$$unique" \
	  || $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	     $$tags $$unique

ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = .
distdir = $(PACKAGE)-$(VERSION)

am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }

GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkinstalldirs) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d $(distdir)/$$subdir \
	    || mkdir $(distdir)/$$subdir \
	    || exit 1; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$(top_distdir)" \
	        distdir=../$(distdir)/$$subdir \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist dist-all: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	$(am__remove_distdir)
	GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(AMTAR) xf -
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && $(mkinstalldirs) "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist-gzip \
	  && rm -f $(distdir).tar.gz \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@echo "$(distdir).tar.gz is ready for distribution" | \
	  sed 'h;s/./=/g;p;x;p;x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(DATA) config.h
installdirs: installdirs-recursive
installdirs-am:
	$(mkinstalldirs) $(DESTDIR)$(bindir) $(DESTDIR)$(bindir) $(DESTDIR)$(docdir)

install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-local mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic distclean-hdr \
	distclean-tags

dvi: dvi-recursive

dvi-am:

info: info-recursive

info-am:

install-data-am: install-data-local install-dist_docDATA

install-exec-am: install-binPROGRAMS install-dist_binSCRIPTS

install-info: install-info-recursive

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
	uninstall-dist_docDATA uninstall-info-am uninstall-local

uninstall-info: uninstall-info-recursive

.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am check check-am clean \
	clean-binPROGRAMS clean-generic clean-local clean-recursive \
	ctags ctags-recursive dist dist-all dist-gzip distcheck \
	distclean distclean-compile distclean-generic distclean-hdr \
	distclean-recursive distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am dvi-recursive info info-am \
	info-recursive install install-am install-binPROGRAMS \
	install-data install-data-am install-data-local \
	install-data-recursive install-dist_binSCRIPTS \
	install-dist_docDATA install-exec install-exec-am \
	install-exec-recursive install-info install-info-am \
	install-info-recursive install-man install-recursive \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am installdirs-recursive maintainer-clean \
	maintainer-clean-generic maintainer-clean-recursive mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-recursive \
	pdf pdf-am pdf-recursive ps ps-am ps-recursive tags \
	tags-recursive uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-dist_binSCRIPTS uninstall-dist_docDATA \
	uninstall-info-am uninstall-info-recursive uninstall-local \
	uninstall-recursive


check:
    # Create new folder, destroy at end. Good example of installation-less
    # creation of a secret folder with the force option
	@./hsencfs -q -l 2 -f -p 1234 ~/.testdata ~/testsecrets
	@-$(srcdir)/enctest.sh
	@-fusermount -u ~/testsecrets
	@-rm -rf ~/testsecrets ~/.testdata

clean-local:
	@-chmod -R u+w hsencfs-*   > /dev/null 2>&1
	@-rm -rf hsencfs-*.rpm     > /dev/null 2>&1
	@-rm -rf hsencfs-*.tar.gz  > /dev/null 2>&1
	@-rm -f $(PAN_SERV)

# We are forcing this to go to /usr/lib as panel will look for it there
# 1.) Generate correct .server file for current bin 2.) Put it in bonobo lib dir
# Allow failure without terminating the build. This is because the distcheck
# will fail on tying to create bonobo files, but it is not an error to fail
# in user mode creating a system file.

install-data-local:
	cat $(srcdir)/$(PAN_SERV).in | \
        sed s%HSTRAY_BIN%$(bindir)/hstray.py% > $(top_builddir)/$(PAN_SERV)
	-$(mkinstalldirs) $(BONOBO_DIR)
	-$(INSTALL) $(top_builddir)/$(PAN_SERV) $(BONOBO_DIR)
	$(mkinstalldirs) $(DESTDIR)/$(datarootdir)/pixmaps
	$(INSTALL) $(srcdir)/hsicon.png  $(DESTDIR)/$(datarootdir)/pixmaps
	$(INSTALL) $(srcdir)/hspadlock.png $(DESTDIR)/$(datarootdir)/pixmaps

uninstall-local:
	-rm -f $(top_builddir)/$(PAN_SERV)
	-rm -f $(BONOBO_DIR)/$(PAN_SERV)
	-rm -f $(DESTDIR)/$(datarootdir)/pixmaps/hsicon.png
	-rm -f $(DESTDIR)/$(datarootdir)/pixmaps/hspadlock.png

gensum:
	-./gensum.sh 

# Make RPMS. To run on an older system, the RPM subsystem needed patching.
# We patched the files as follows:
#
# 1.) Added redirect (>>rpmwarn) to /usr/lib/rpm/check-files.sh
# The check delivers a warning instead of an error. Context:
#
# while read f; do
#   echo $f | sed -e "s#^$RPM_BUILD_ROOT#   #g" >> rpmwarn
# done
#
# 2.) Commented out strict=true line in /usr/lib/rpm/find-debuginfo.sh
# The check delivers a warning instead of an error.  Context:
#
# while [ $# -gt 0 ]; do
#  case "$1" in
#  --strict-build-id)
#    #strict=true
#    ;;
#
# All this was necessary to allow both RPM build and distcheck to pass.

rpm: rpm-src rpm-bin

rpm-src:  dist
	rpmbuild -ts hs*.tar.gz
	-cp ~/rpmbuild/SOURCES/hsenc*.rpm $(top_builddir)
	@echo  "*******************************************"
	@echo  Done RPM SRC Creation. SRPM in current dir
	@echo  "*******************************************"

rpm-bin:  dist
	rpmbuild -tb *.tar.gz
	-cp ~/rpmbuild/RPMS/`uname -m`/hsenc*.rpm $(top_builddir)
	@echo  "*******************************************"
	@echo  Done RPM Creation. RPM in current dir
	@echo  "*******************************************"

# Execute the whole creation / check / packaging cycle
cycle: gensum dist distcheck rpm
	@echo
	@echo  "***************"
	@echo  Done Cycle Check.
	@echo  "***************"

# Use only for testing / development. Will hard erase all of HSENC.
hard-remove:
	$(srcdir)/hard-remove.sh

# Wanted to look ... you may be curious too. Just add as a dependency.
test-vars:
	@echo  top_builddir=$(top_builddir)
	@echo  dc_install_base=$$dc_install_base
	@echo  dc_destdir=$(dc_destdir)
	@echo  DESTDIR=$(DESTDIR)
	@echo  bindir=$(bindir)
	@echo  srcdir=$(srcdir)
	@echo  prefix=$(prefix)
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
